# No need for API documentation.
Documentation:
  Enabled: false

AllCops:
  Exclude:
    - config/initializers/secret_token.rb
    - bin/**/*
    - db/**/*
    - Guardfile

AbcSize:
  Exclude:
    - lib/metadata/**/*

ClassLength:
  Exclude:
    - lib/metadata/saml.rb

MethodLength:
  Exclude:
    - lib/metadata/saml.rb